Web/Controllers/DashboardController.cs
using KPI_ONLINE.DAL.TKPI_USER_DAL;
using KPI_ONLINE.DAL.Utilities;
using KPI_ONLINE.Models;
using KPI_ONLINE.Utilitie;
using KPI_ONLINE.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Web.Models;
using Web.Utilitie;
using static KPI_ONLINE.ViewModel.DashboardViewModel;

namespace Web.Controllers
{
    [MenuAuthorize(ConstantPrm.MenuAuthorize.DASHBOARD_MENU)]
    public class DashboardController : BaseController
    {
        [MenuAuthorize(ConstantPrm.MenuAuthorize.DASHBOARD_MENU)]
        public ActionResult Index()
        {
            var pModel = new ReportExcrusiveKPIViewModel();
            GetUrlParameter(Request, "userID");
            var serviceModel = new ReportExcusiveKPIServiceModel();
            var searchCriteria = pModel.Criteria;
            searchCriteria.Year = DateTime.Now.Year.ToString();
            searchCriteria.PeriodType = "Year";
            var serviceDD = new SetDropDownList();
            pModel.ColorScaleCode = serviceDD.GetColorScaleCode();
            serviceModel.GetSearchResult(pModel,true);
            return View(pModel);
        }
        private string GetUrlParameter(HttpRequestBase request, string parName)
        {
            string result = string.Empty;
            TKPI_USERS_DAL dal = new TKPI_USERS_DAL();
            var urlParameters = HttpUtility.ParseQueryString(request.Url.Query);
            if (urlParameters.AllKeys.Contains(parName))
            {
                result = urlParameters.Get(parName);
            }
            if(!string.IsNullOrEmpty(result))
            {
                ShareFn fn = new ShareFn();
                UnitOfWork unitOfWork = new UnitOfWork();
                var dataUser = dal.GetUserByUserName(result, ref unitOfWork);
                if(dataUser != null)
                {
                    UserModel user = new UserModel();

                    user.UserName = result;
                    user.EmployeeId = dataUser.TKU_USER_CODE;
                    user.Name = string.Format("{0} {1}", dataUser.TKU_FIRST_NAME, dataUser.TKU_LAST_NAME);
                    user.RoleId = dataUser.TKR_ID;
                    user.RoleName = dataUser.TKPI_ROLE.TKR_NAME;
                    user.CompanyName = dataUser.TKPI_MASTER_COMPANY.TKC_COM_NAME;
                    user.ImagePath = fn.GetPathofPersonalImg(Convert.ToInt64(dataUser.TKU_USER_CODE), dataUser.TKPI_MASTER_COMPANY.TKC_COM_NAME);

                    Const.User = user;
                    Const.User.AuthenView(ref unitOfWork);
                }
                
            }

            return result;
        }

        [HttpPost]
        public string GenerateExcel1()
        {
            var fn1 = new ReportKPIPerformaceAreaServiceModel();
            var file_name = fn1.GenerateExcel();

            return file_name;
        }

        [HttpPost]
        public string GenerateExcel2()
        {
            var fn2 = new ReportKPIResultDashboardServiceModel();
            var file_name = fn2.GenerateExcel();

            return file_name;
        }

        public JsonResult GraphKPI()
        {
            List<Series> series = new List<Series>();
            //SCALE1
            Series scale1 = new Series();
            List<Object> dataGenGraphList = new List<Object>();
            for (int i = 0; i < 16; i++)
            {
                if (i == 1 || i == 5 || i == 8)
                {
                    dataGenGraphList.Add(1);
                }
                else {
                    dataGenGraphList.Add(null);
                }
            }
            //data Graph
            scale1.data = dataGenGraphList;
            scale1.name = "Scale1";
            //scale1.type = "";
            scale1.tooltip = new Tooltip(false, "");
            scale1.marker = new Marker(true);
            scale1.yAxis = 0;
            scale1.color = "#FF0000";
            series.Add(scale1);
            //SCALE2
            Series scale2 = new Series();
            dataGenGraphList = new List<Object>();
            for (int i = 0; i < 16; i++)
            {
                if (i == 2 || i == 6 || i == 12)
                {
                    dataGenGraphList.Add(2);
                }
                else
                {
                    dataGenGraphList.Add(null);
                }
            }
            scale2.data = dataGenGraphList;
            scale2.name = "Scale2";
            //scale2.type = "bar";
            scale2.tooltip = new Tooltip(false, "");
            scale2.marker = new Marker(true);
            scale2.yAxis = 0;
            scale2.color = "#ffff00";
            series.Add(scale2);
            //SCALE3
            Series scale3 = new Series();
            dataGenGraphList = new List<Object>();
            for (int i = 0; i < 16; i++)
            {
                if (i == 0 || i == 7 || i == 9 || i == 15)
                {
                    dataGenGraphList.Add(3);
                }
                else
                {
                    dataGenGraphList.Add(null);
                }
            }
            scale3.data = dataGenGraphList;
            scale3.name = "Scale3";
            //scale3.type = "bar";
            scale3.tooltip = new Tooltip(false, "");
            scale3.marker = new Marker(true);
            scale3.yAxis = 0;
            scale3.color = "#7CFC00";
            series.Add(scale3);
            //SCALE4
            Series scale4 = new Series();
            dataGenGraphList = new List<Object>();
            for (int i = 0; i < 16; i++)
            {
                if (i == 3 || i == 10 || i == 13)
                {
                    dataGenGraphList.Add(4);
                }
                else
                {
                    dataGenGraphList.Add(null);
                }
            }
            scale4.data = dataGenGraphList;
            scale4.name = "Scale4";
            //scale4.type = "bar";
            scale4.tooltip = new Tooltip(false, "");
            scale4.marker = new Marker(true);
            scale4.yAxis = 0;
            scale4.color = "#7CFC00";
            series.Add(scale4);
            //SCALE5
            Series scale5 = new Series();
            dataGenGraphList = new List<Object>();
            for (int i = 0; i < 16; i++)
            {
                if (i == 4 || i == 11 || i == 14)
                {
                    dataGenGraphList.Add(5);
                }
                else
                {
                    dataGenGraphList.Add(null);
                }
            }
            scale5.data = dataGenGraphList;
            scale5.name = "Scale5";
            //scale5.type = "bar";
            scale5.tooltip = new Tooltip(false, "");
            scale5.marker = new Marker(true);
            scale5.yAxis = 0;
            scale5.color = "#7CFC00";
            series.Add(scale5);

            Graph graph = new Graph();
            graph.Series = series;

            return Json(graph, JsonRequestBehavior.AllowGet);

        }
    }
}

Web/Controllers/ReportMapController.cs
using KPI_ONLINE.Models;
using KPI_ONLINE.Utilitie;
using KPI_ONLINE.ViewModel;
using System;
using System.IO;
using System.Linq;
using System.Web.Mvc;
using Web.Controllers;
using Web.Utilitie;

namespace KPI_ONLINE.Controllers
{
    public class ReportMapController : BaseController
    {
        // GET: Map
        ReportMapServiceModel _ = new ReportMapServiceModel();
        [MenuAuthorize(ConstantPrm.MenuAuthorize.MAP_REPORT_MENU)]
        public ActionResult Index()
        {
            var Model = new ReportMapViewModel();
            Model.Criteria.Year = DateTime.Now.Year.ToString();
            Model.Criteria.PeriodType = "Year";
            InitialSearchCritiria(Model);
            _.GetSearchResult(Model);
            //_.CombineImages(Model);
            return View("Index", Model);
        }
        [HttpPost]
        [MultipleButton(Name = "action", Argument = "Search")]
        [MenuAuthorize(ConstantPrm.MenuAuthorize.MAP_REPORTT_ACTION)]
        public ActionResult Search(ReportMapViewModel pModel)
        {
            var serviceModel = new ReportMapServiceModel();
            var roleserviceModel = new RoleServiceModel();
            _.GetSearchResult(pModel);
            InitialSearchCritiria(pModel);
            return View("Index", pModel);
        }
        public void InitialSearchCritiria(ReportMapViewModel Model)
        {
            var searchCriteria = Model.Criteria;
            var serviceModel = new SetDropDownList();
            searchCriteria.ddKPIIndicator = serviceModel.GetKPI(Const.User.AuthKpiIdLs);
            searchCriteria.ddPeriodType = serviceModel.GetPeriodType();
            searchCriteria.ddTargetPeriod = serviceModel.GetTargetPeriod(Model.Criteria.PeriodType);
            searchCriteria.ddYear = serviceModel.GetYear();

        }
        [HttpPost]
        [MenuAuthorize(ConstantPrm.MenuAuthorize.MAP_REPORTT_ACTION)]
        public ActionResult PlantKPIDetail(string Plant, string Shift, string kpiNo, string targetperiod, string year, string periodtype)
        {
            PlantKPIDetail model = new PlantKPIDetail();
            _.GetPlantKPIDetail(model, Plant, Shift, kpiNo, targetperiod, year, periodtype);
            return PartialView("_PlatKPIDetailView", model);
        }
        [HttpPost]
        public ActionResult MapConfig()
        {
            MapConfig model = new MapConfig();
            _.GetMapConfig(model);

            return PartialView("_MapConfig", model);
        }

        [HttpPost]
        [MultipleButton(Name = "action", Argument = "SaveMapConfig")]
        [MenuAuthorize(ConstantPrm.MenuAuthorize.MAP_REPORT_MENU)]
        public ActionResult SaveMapConfig(MapConfig model)
        {
            var rtn = _.SaveMapConfig(model);
            return Index();
        }

        public ActionResult LoadExcel(string file_path)
        {
            string root_path = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "FileUpload");
            string file_name = file_path.Replace(root_path + "\\", "");
            var byteArr = System.IO.File.ReadAllBytes(root_path + "\\" + file_path);
            return File(byteArr, "application/vnd.ms-excel", file_path);
        }

        public ActionResult ExportExcel(string pPeriod_Type, string pTarget_Period, string pYear, string pKpi)
        {
            ReportMapViewModel pModel = new ReportMapViewModel();
            pModel.Criteria.PeriodType = pPeriod_Type;
            pModel.Criteria.TargetPeriod = pTarget_Period;
            pModel.Criteria.Year = pYear;
            pModel.Criteria.KPIIndicator = pKpi;
            string file_path = _.CreateExcel(pModel);
            string root_path = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "FileUpload");
            string file_name = file_path.Replace(root_path + "\\", "");
            return new JsonResult()
            {
                Data = new { FileName = file_name }
            };
        }

    }



}

Web/Views/Shared/_Layout.cshtml
@using Web.Utilitie

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:300,300i,400,400i,500,500i%7COpen+Sans:300,300i,400,400i,600,600i,700,700i" rel="stylesheet">
    <link rel="icon" type="image/png" href="~/favicon.ico" />
    <title>@ViewBag.Title - KPI Application</title>
    @Styles.Render("~/Content/css")
    @*@Scripts.Render("~/bundles/jsvalidator")*@
</head>
<body class="vertical-layout vertical-menu-modern 2-columns   fixed-navbar" data-open="click" data-menu="vertical-menu-modern" data-col="2-columns">
    <!-- BEGIN: Header-->
    <nav class="header-navbar navbar-expand-lg navbar navbar-with-menu fixed-top navbar-semi-dark navbar-shadow">
        <div class="navbar-wrapper">
            <div class="navbar-header">
                <ul class="nav navbar-nav flex-row">
                    <li class="nav-item mobile-menu d-lg-none mr-auto"><a class="nav-link nav-menu-main menu-toggle hidden-xs" href="#"><i class="ft-menu font-large-1"></i></a></li>
                    <li class="nav-item mr-auto">
                        <a class="navbar-brand" href="@Url.Action("Index", "Dashboard")" style="padding-top: 5px;">
                            <img class="brand-logo" alt="stack admin logo" src="~/Content/app-assets/images/logo/Thaioil_Corporate_Logo_x.png" style="height: 40px;">
                            <h2 class="brand-text" style="float: right;margin: 10px -10px -10px 0px;font-weight: bold;padding-bottom: -10px;color: #da288b;line-height: 0.7;font-family: fantasy;"> 
                                KPI
                                <span style="color:#da288b; white-space: pre-line;" class="font-medium-3"> 
                                    Dashboard
                                </span> 
                            </h2>
                        </a>
                    </li>
                    <li class="nav-item d-none d-lg-block nav-toggle"><a class="nav-link modern-nav-toggle pr-0" data-toggle="collapse"><i class="toggle-icon ft-toggle-right font-medium-3 white" data-ticon="ft-toggle-right"></i></a></li>
                    @*<li class="nav-item d-lg-none"><a class="nav-link open-navbar-container" data-toggle="collapse" data-target="#navbar-mobile"><i class="fa fa-ellipsis-v"></i></a></li>*@
                </ul>
            </div>
            <div class="navbar-container content">
                <div class="collapse navbar-collapse" id="navbar-mobile">
                    <ul class="nav navbar-nav mr-auto float-left">

                        @*<li class="nav-item d-none d-md-block"><a class="nav-link nav-link-expand" href="#"><i class="ficon ft-maximize"></i></a></li>*@
                        @*<li class="nav-item nav-search">
                                <a class="nav-link nav-link-search" href="#"><i class="ficon ft-search"></i></a>
                                <div class="search-input">
                                    <input class="input" type="text" placeholder="Explore Stack...">
                                </div>
                            </li>*@
                    </ul>
                    <ul class="nav navbar-nav float-right">
                        <li class="dropdown dropdown-user nav-item">
                            <a class="dropdown-toggle nav-link dropdown-user-link" href="#" data-toggle="dropdown"><span class="avatar avatar-online"><img src="@ViewData["empImage"]" alt="image"><i></i></span><span class="user-name">@ViewData["lbUserName"]</span></a>

                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </nav>
    <!-- END: Header-->
    <!-- BEGIN: Main Menu-->
    <div class="main-menu menu-fixed menu-dark menu-accordion menu-shadow" data-scroll-to-active="true" style="touch-action: none; user-select: none; -webkit-user-drag: none; -webkit-tap-highlight-color: rgba(0, 0, 0, 0);">
        <div class="main-menu-content ps" style="height: 734px;">
            <ul class="navigation navigation-main" id="main-menu-navigation" data-menu="menu-navigation">

                @{
                    if (ViewContext.HttpContext.User.IsInRole(ConstantPrm.MenuAuthorize.DASHBOARD_MENU))
                    {
                        <li class="nav-item">
                            <a class="menu-item" href="@Url.Action("Index", "Dashboard")"><i class="ft-home"></i><span class="menu-title" data-i18n="">@ConstantPrm.MenuAuthorize.DASHBOARD_MENU</span></a>
                        </li>
                    }
                    if (ViewContext.HttpContext.User.IsInRole(ConstantPrm.MenuAuthorize.ADMIN_MENU))
                    {
                        <li class="nav-item has-sub">
                            <a href="#"><i class="ft-users"></i><span class="menu-title" data-i18n="">@ConstantPrm.MenuAuthorize.ADMIN_MENU</span></a>
                            <ul class="menu-content" style="">

                                @if (ViewContext.HttpContext.User.IsInRole(ConstantPrm.MenuAuthorize.USER_MENU))
                                {
                                    <li><a class="menu-item" href="@Url.Action("User", "Master")">@ConstantPrm.MenuAuthorize.USER_MENU</a></li>
                                }

                                @if (ViewContext.HttpContext.User.IsInRole(ConstantPrm.MenuAuthorize.PIS_MENU))
                                {
                                    <li> <a class="menu-item" href="@Url.Action("UserMonitor", "Master")">@ConstantPrm.MenuAuthorize.PIS_MENU</a></li>
                                }

                                @if (ViewContext.HttpContext.User.IsInRole(ConstantPrm.MenuAuthorize.ROLE_MENU))
                                {
                                    <li> <a class="menu-item" href="@Url.Action("Role", "Master")">@ConstantPrm.MenuAuthorize.ROLE_MENU</a></li>
                                }

                                @if (ViewContext.HttpContext.User.IsInRole(ConstantPrm.MenuAuthorize.KPI_MANAGE_MENU))
                                {
                                    <li><a class="menu-item" href="@Url.Action("IndicatorsManage", "Master")">@ConstantPrm.MenuAuthorize.KPI_MANAGE_MENU</a></li>
                                }

                            </ul>
                        </li>
                    }

                    if (ViewContext.HttpContext.User.IsInRole(ConstantPrm.MenuAuthorize.REPORT_MENU))
                    {
                        <li class="nav-item has-sub">
                            <a href="#"><i class="ft-file-text"></i><span class="menu-title" data-i18n="">@ConstantPrm.MenuAuthorize.REPORT_MENU</span></a>
                            <ul class="menu-content" style="">

                                @if (ViewContext.HttpContext.User.IsInRole(ConstantPrm.MenuAuthorize.EXECUTIVE_REPORT_MENU))
                                {
                                    <li><a class="menu-item" href="@Url.Action("Index","ReportExcrusiveKPI")">Report Executive KPI</a></li>
                                }

                                @if (ViewContext.HttpContext.User.IsInRole(ConstantPrm.MenuAuthorize.KPI_PERFORMANCE_REPORT_MENU))
                                {
                                    <li> <a class="menu-item" href="@Url.Action("Index","ReportKPISummaryPerformance")">Report Summary Performance</a></li>
                                }

                                @if (ViewContext.HttpContext.User.IsInRole(ConstantPrm.MenuAuthorize.KPI_SUMMARY_MENU))
                                {
                                    <li> <a class="menu-item" href="@Url.Action("Index","VpAndPomKPIResultReport")">Report VP and POM KPI</a></li>
                                }


                                @if (ViewContext.HttpContext.User.IsInRole(ConstantPrm.MenuAuthorize.KPI_DETAIL_REPORT_MENU))
                                {
                                    <li><a class="menu-item" href="@Url.Action("Index","KPIDetailAreaReport")">KPI Detail Area Report</a></li>
                                }

                                @if (ViewContext.HttpContext.User.IsInRole(ConstantPrm.MenuAuthorize.MAP_REPORT_MENU))
                                {
                                    <li><a class="menu-item" href="@Url.Action("Index","ReportMap")">Map View</a></li>
                                }
                            </ul>
                        </li>
                    }


                    if (ViewContext.HttpContext.User.IsInRole(ConstantPrm.MenuAuthorize.IMPORT_MENU))
                    {
                        <li class="nav-item">
                            <a class="menu-item" href="@Url.Action("Search","ImportKPIData")"><i class="ft-upload-cloud"></i><span class="menu-title" data-i18n="">Import Data</span></a>
                        </li>
                    }



                }




            </ul>
            <div class="ps__rail-x" style="left: 0px; bottom: 0px;"><div class="ps__thumb-x" tabindex="0" style="left: 0px; width: 0px;"></div></div><div class="ps__rail-y" style="top: 0px; right: 0px;"><div class="ps__thumb-y" tabindex="0" style="top: 0px; height: 0px;"></div></div>
        </div>
    </div>

    <!-- BEGIN: Content-->
    @Scripts.Render("~/bundles/helper")
    @*@Scripts.Render("~/bundles/themejs")*@
    @Scripts.Render("~/bundles/modernizr")
    @*@Scripts.Render("~/bundles/jquery")*@
    @Scripts.Render("~/bundles/moment")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/jqueryval")

    @Scripts.Render("~/bundles/bootbox")


    @*@Scripts.Render("~/bundles/datatables")*@
    @Scripts.Render("~/bundles/bootstrap-toggle")
    @Scripts.Render("~/bundles/datepicker")
    @Scripts.Render("~/bundles/alertify")
    @Scripts.Render("~/bundles/loader")
    @Scripts.Render("~/bundles/bootstrap-treeview")

    @RenderSection("scripts", required: false)

    <input type="hidden" id="AppName" value="@System.Configuration.ConfigurationManager.AppSettings["AppName"]" />

    <div class="app-content content">
        <div class="content-body">

            @RenderBody()

        </div>
    </div>

    <!-- END: Content-->

    <div class="sidenav-overlay"></div>
    <div class="drag-target"></div>

    @Html.Hidden("URL_GetArea_DDL", Url.Action("GetAreaByDepartmentDDL", "Master"))
    @Html.Hidden("URL_GetPlant_DDL", Url.Action("GetPlantByAreaDDL", "Master"))
    @Html.Hidden("URL_GetShift_DDL", Url.Action("GetShiftByPlantDDL", "Master"))

    <div class="loader" style="display:none;">
        <div class="loader-inner ball-grid-pulse">
            <div></div>
            <div></div>
            <div></div>
            <div></div>
            <div></div>
            <div></div>
            <div></div>
            <div></div>
            <div></div>
        </div><span class="tooltip">
            <p>ball-grid-pulse</p>
        </span>
    </div>


</body>
</html>